/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package P2PChatSystem;

public class ChatPeer {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        System.out.println(new ChatPeer().getGreeting());
    }
}
